services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: my-list
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .               
      dockerfile: MyList.Api/Dockerfile
    ports:
      - "5050:8080"       
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=my-list;Username=${POSTGRES_USER};Password=${POSTGRES_PASS}"
    depends_on:
      - postgres

  scraper:
    build:
      context: .
      dockerfile: MyList.Scraper/Dockerfile
    environment:
      ApiBaseUrl: "http://api:8080"
    depends_on:
      - api
  
  notifier: 
    build: 
      context: .
      dockerfile: MyList.Notifier/Dockerfile
    environment: 
      ApiBaseUrl: "http://api:8080"
      Smtp__Host: "smtp.gmail.com"
      Smtp__Port: "587"
      Smtp__Username: ${SMTP_USER}
      Smtp__Password: ${SMTP_PASS}
    depends_on: 
      - api

volumes:
  pgdata:
