services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my-list
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .               
      dockerfile: MyList.Api/Dockerfile
    ports:
      - "5050:8080"       
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=my-list;Username=postgres;Password=postgres"
    depends_on:
      - postgres

  scraper:
    build:
      context: .
      dockerfile: MyList.Scraper/Dockerfile
    environment:
      ApiBaseUrl: "http://api:8080"
    depends_on:
      - api

volumes:
  pgdata:
